### ISSUE TITLE
Compatibility with Aframe 1.3.0

### ISSUE THREAD

**Issue by calvincs** [ryota-mitarai/aframe-websurfaces#4]
When using AFrame 1.3.0, the following error occurs:
```ruby

aframe-websurfaces.umd.js:1 Uncaught TypeError: Class constructor Mesh cannot be invoked without 'new'
    at new n (aframe-websurfaces.umd.js:1:4354)
    at HTMLElement.<anonymous> (aframe-websurfaces.umd.js:1:7158)
    at HTMLElement.<anonymous> (aframe-v1.3.0.min.js:45177:2943)
    at i.tick (aframe-websurfaces.umd.js:1:7873)
    at HTMLElement.value (aframe-v1.3.0.min.js:45187:12868)
    at HTMLElement.value (aframe-v1.3.0.min.js:45187:13402)
    at aframe-v1.3.0.min.js:45324:132
    at onAnimationFrame (aframe-v1.3.0.min.js:20088:34)
    at onAnimationFrame (aframe-v1.3.0.min.js:9547:4)
```

**Comment by calvincs** [comment]
Easy fix found.  Replace all instances of THREE with AFRAME.THREE.

This corrected the issue for me

**Comment by carlosveny** [comment]
I'm also having this issue. Any fix?

**Comment by calvincs** [comment]
I reverted to aframe 1.2.0
This was my only way of resolving this issue.  I plan on looking to patch a fork of this lib in the future for aframe 1.3.0.   The underlying threejs is many versions behind for this project and needs to be patched to be compatible with the same threejs version aframe 1.3.0 is using.

**Comment by carlosveny** [comment]
Okay thanks for your reply!

**Comment by dannypbroadbent** [comment]
Getting the same issue for v1.3 of AFrame, are there plans to update this?

**Comment by addy1997** [comment]
Did anyone find a work around for this incompatibility issue?
